Use ARN as external name for aws_iam_role
crossplane-contrib/provider-upjet-aws pull request #1380
Opened 2024-06-26 07:34 UTC by gadiener

### Description of your changes

In this PR I'm changing the external name for `aws_iam_role` to use the ARN instead of the role name. Role names are not unique IDs and it is possible to have in the same AWS account multiple role with the same name but with different paths.

I see the [Terraform provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role#import) is also using the role name as ID please let me know if you have a better suggestion.

Fixes #1376 

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

Still need to test

[contribution process]: https://git.io/fj2m9

2024-06-26 11:21 UTC, gadiener commented
/test-examples="examples/iam/v1beta1/role.yaml"

2024-06-26 11:22 UTC, gadiener commented
/test-examples="examples/iam/v1beta1/rolepolicy.yaml"

2024-06-26 11:35 UTC, gadiener commented
I just found the file `/config/externalname.go` would it be better to apply this change there?

2024-06-26 13:04 UTC, gadiener commented
/test-examples="examples/iam/v1beta1/role.yaml"

2024-06-26 14:41 UTC, gadiener commented
Hi @turkenf sorry for pinging you directly. 
I'd really appreciate a comment from you on the solution and an hint on what is going on with the failing tests.
Thanks

2024-06-26 15:08 UTC, turkenf commented
Hi @gadiener,

Many thanks for your interest and effort. I won't be able to look at this PR soon due to other priorities. But I will try to look at this next week.

2024-06-26 15:28 UTC, gadiener commented
Thanks a lot @turkenf 🙏🏻

2024-06-29 22:17 UTC, mbbush requested changes
This will not work in its current state. Your change to the external name configuration results in a breaking schema change, but the code generation pipeline before showing you that breaking change due to some less-than-ideal implementations.

It should be possible to change the external name configuration without changing the CRD schema. Our convention is that such configuration belongs in `config/externalname.go`. But before you work on that let's have a conversation about what the external name *should* be. 

I saw the issue you opened, and will comment further there.

2024-07-01 08:15 UTC, gadiener commented
Sure, let's discuss in the issue. I'll keep that open for now

2024-07-04 07:14 UTC, gadiener commented
https://github.com/crossplane-contrib/provider-upjet-aws/issues/1376#issuecomment-2208275584

2024-07-04 07:14 UTC, gadiener commented
https://github.com/crossplane-contrib/provider-upjet-aws/issues/1376#issuecomment-2208275584

2024-07-04 07:14 UTC, closed without merging